/data/lpn/miniconda3/envs/fgprompt/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/data/lpn/miniconda3/envs/fgprompt/bin/python: can't open file 'run.py': [Errno 2] No such file or directory
/data/lpn/miniconda3/envs/fgprompt/bin/python: can't open file 'run.py': [Errno 2] No such file or directory
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 2) local_rank: 0 (pid: 25465) of binary: /data/lpn/miniconda3/envs/fgprompt/bin/python
Traceback (most recent call last):
  File "/data/lpn/miniconda3/envs/fgprompt/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/lpn/miniconda3/envs/fgprompt/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/lpn/miniconda3/envs/fgprompt/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/data/lpn/miniconda3/envs/fgprompt/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/data/lpn/miniconda3/envs/fgprompt/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/data/lpn/miniconda3/envs/fgprompt/lib/python3.8/site-packages/torch/distributed/run.py", line 715, in run
    elastic_launch(
  File "/data/lpn/miniconda3/envs/fgprompt/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/data/lpn/miniconda3/envs/fgprompt/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
run.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-05-24_20:41:34
  host      : 68
  rank      : 1 (local_rank: 1)
  exitcode  : 2 (pid: 25466)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-05-24_20:41:34
  host      : 68
  rank      : 0 (local_rank: 0)
  exitcode  : 2 (pid: 25465)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
/data/lpn/miniconda3/envs/fgprompt/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/data/lpn/miniconda3/envs/fgprompt/bin/python: can't open file 'run_debug_train.py': [Errno 2] No such file or directory
/data/lpn/miniconda3/envs/fgprompt/bin/python: can't open file 'run_debug_train.py': [Errno 2] No such file or directory
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 2) local_rank: 0 (pid: 29249) of binary: /data/lpn/miniconda3/envs/fgprompt/bin/python
Traceback (most recent call last):
  File "/data/lpn/miniconda3/envs/fgprompt/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/lpn/miniconda3/envs/fgprompt/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/lpn/miniconda3/envs/fgprompt/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/data/lpn/miniconda3/envs/fgprompt/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/data/lpn/miniconda3/envs/fgprompt/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/data/lpn/miniconda3/envs/fgprompt/lib/python3.8/site-packages/torch/distributed/run.py", line 715, in run
    elastic_launch(
  File "/data/lpn/miniconda3/envs/fgprompt/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/data/lpn/miniconda3/envs/fgprompt/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
run_debug_train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-05-24_20:42:49
  host      : 68
  rank      : 1 (local_rank: 1)
  exitcode  : 2 (pid: 29250)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-05-24_20:42:49
  host      : 68
  rank      : 0 (local_rank: 0)
  exitcode  : 2 (pid: 29249)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
/data/lpn/miniconda3/envs/fgprompt/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/data/lpn/miniconda3/envs/fgprompt/bin/python: can't open file 'run_debug_train.py': [Errno 2] No such file or directory
/data/lpn/miniconda3/envs/fgprompt/bin/python: can't open file 'run_debug_train.py': [Errno 2] No such file or directory
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 2) local_rank: 0 (pid: 38158) of binary: /data/lpn/miniconda3/envs/fgprompt/bin/python
Traceback (most recent call last):
  File "/data/lpn/miniconda3/envs/fgprompt/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/lpn/miniconda3/envs/fgprompt/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/lpn/miniconda3/envs/fgprompt/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/data/lpn/miniconda3/envs/fgprompt/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/data/lpn/miniconda3/envs/fgprompt/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/data/lpn/miniconda3/envs/fgprompt/lib/python3.8/site-packages/torch/distributed/run.py", line 715, in run
    elastic_launch(
  File "/data/lpn/miniconda3/envs/fgprompt/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/data/lpn/miniconda3/envs/fgprompt/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
run_debug_train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-05-24_20:45:44
  host      : 68
  rank      : 1 (local_rank: 1)
  exitcode  : 2 (pid: 38159)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-05-24_20:45:44
  host      : 68
  rank      : 0 (local_rank: 0)
  exitcode  : 2 (pid: 38158)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
